### ISSUE TITLE
Ships problems

### ISSUE THREAD

**Issue by shiryux** [Sphereserver/Source-experimental#216] opened 2019-01-25 17:13 UTC
I've been having different problems with ships.

1. Trying to board from planks sends to the opposite side of land, so you never board the ship.
2. Walking when the ship is moving, sometimes, can make you "fall" to the water.
3. You can't see what is outside the ship, example, add a ship on Britain's dock, move the ship away from the dock, come back and you won't see any char or dynamic item.

Could not reproduce but happened:
Similar happens when you get off the ship through the plank, you walk a little afterwards and you can get a wrong Z level.

Suggestion:
Porting of this commit would be nice: https://github.com/Sphereserver/Source/commit/cd2513c1e20a1288162d461067c99610b72d05dc#diff-824b80dc08bda51376a5a5aad994302f

**Comment by shiryux** [comment] 2019-01-27 22:59
Yes, it is enabled.

**Comment by cbnolok** [comment] 2019-01-28 23:35
1) Can't reproduce;
2) It appears to be an issue only when using smooth sailing, and it's easier if you have gm mode enabled, maybe we should use the new movement packet to fix this;
3) Should be fixed with last commit

**Comment by azmanomer** [comment] 2019-01-29 02:31
i can confirm you can fall to the water while ship is moving. i can reproduce it like add i_deed_small_ship_n enable speedmode 1 then command forward to ship while moving just run from at the edge of the ship from front to back.
![resim](https://user-images.githubusercontent.com/13722155/51880109-14eacc80-2387-11e9-9d87-0c179bd25983.png)

**Comment by shiryux** [comment] 2019-01-29 23:48
1. I can reproduce it still. Try boarding with walking instead of dclick.
2. I'll try to play around without smooth sailing.

**Comment by AtillaG1** [comment] 2019-02-04 23:11
cant reproduce it aswell..
using smooth sail

**Comment by GitMadKing** [comment] 2019-02-07 22:34
also i can confirm this and how to replicate.
https://streamable.com/6n0rm

**Comment by cbnolok** [comment] 2019-02-14 21:56
Can you replicate with the latest commit?

**Comment by shiryux** [comment] 2019-02-14 22:06
No, it seems fixed, I can get in/out perfectly with or without GM.

**Closed** 2019-02-18 02:28 UTC
Labels: more info needed
