### ISSUE TITLE
Client crash when gm char die at the same screen with plvl 1 char

### ISSUE THREAD

**Issue by azmanomer** [Sphereserver/Source-experimental#38] opened 2018-03-26 16:47 UTC
To duplicate this : 
1 x plevel 7 char 
1 x plevel 1 char
login both of them and kill plevel 7 char they should be in same screen. plevel 1 char's client will crash. i tried it with 7.0.61 client , 7.0.18, 7.0.20 , 6x client still all of them crashed. and console gave this : 
Client crashed at 0,0,0,0: 0xC0000005 CRASH @ 0x7546900E (client_7.0.18.0_HS.exe, 7.0.18.0)

plevel 7 char's client is not crashing.

**Comment by cbnolok** [comment] 2018-03-26 20:15
I can't replicate this every time, it has happened only once in like 15 tries and both clients crashed. I couldn't log in again with both characters because they crashed, but i was able to log in with the Enhanced Client. I removed a gargish item from the char's corpse, then i was able to log in again with the Classic Client.
I don't know how much this is a Sphere problem, anyways do one of your clients have strange items in the backpack? Like gargish or high id items? Does it help to enable all of the feature flags in the .ini?

**Comment by azmanomer** [comment] 2018-03-26 21:24
yeah i removed gargish items its not crashing anymore.

**Comment by azmanomer** [comment] 2018-03-26 21:34
even all feature flags enabled its still crashing if i gm char wearing gargish item its crashing

**Comment by cbnolok** [comment] 2018-03-26 21:36
And what about if both chars are gargoyles?

>

**Comment by cbnolok** [comment] 2018-03-28 13:13
Adding some info if someone will have this problem:
if both chars are gargoyles, the classic client won't crash; it seems that that client has problems with gargoyle items inside a human/elf corpse.
This specific issue was caused by gargoyle items incorrectly being added at the character creation for a human or elf player. This was fixed in the last commit.

**Closed by cbnolok** 2018-03-28 13:13 UTC
